services:
  db:
    image: postgres:16.4
    container_name: vrcursos-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: vrcourses
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres-data
